######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 3 15:01:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Task.h \
    taskpool.h
SOURCES += main.cpp Task.cpp \
    taskpool.cpp


