######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 3 15:01:43 2013
######################################################################

QT       += core

QT       -= gui

TARGET = rdv_interview
CONFIG   += console
CONFIG   -= app_bundle

TEMPLATE = app


SOURCES += main.cpp Task.cpp \
    taskpool.cpp
HEADERS += Task.h \
    taskpool.h
